config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :products
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  root 'static_pages#landing_page'

  resources :orders, only: [:index, :show, :new, :create]

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :orders
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index

  end

  def show

  end

  def new

  end

  def create

  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :colour, :description, :image_url)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def landing_page
    @products = Product.limit(3)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title SampleApp
    %link{href: 'http://fonts.googleapis.com/css?family=Lato|Lora', rel: 'stylesheet', type: 'text/css'}
    %link{href: '//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css', rel: 'stylesheet'}
    = stylesheet_link_tag('application', media: 'all', 'data-turbolinks-track' => true)
    = javascript_include_tag('application', 'data-turbolinks-track' => true)
    %script{src: '//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js'}

    = csrf_meta_tags

  %body
    %div.container
      = render 'shared/nav'

      %h1 Welcome to Ruhe Farm
      %h2 Your source for local organic vegetables in New Brunswick

      %p.notice= notice
      %p.alert= alert

      = yield

app/views/orders/index.html.haml
!!! html
%html
  %head{lang: "en"}
    %meta{charset: "UTF-8"}
    %title

  %body

app/views/orders/new.html.haml
!!! html
%html
  %head{lang: "en"}
    %meta{charset: "UTF-8"}
    %title

  %body

app/views/orders/show.html.haml
!!! html
%html
  %head{lang: "en"}
    %meta{charset: "UTF-8"}
    %title

  %body

app/views/products/_form.html.haml
= form_for @product, html: {class: 'form-horizontal'} do |f|
  - if @product.errors.any?
    %div#error_explanation
      %h2= "#{pluralize(@product.errors.count, 'error')} prohibited this product from being saved:"

      %ul
        - @product.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.label :name, class: 'control-label col-sm-2'
    .col-sm-5
      = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :colour, class: 'control-label col-sm-2'
    .col-sm-3
      = f.text_field :colour, class: 'form-control'
  .form-group
    = f.label :description, class: 'control-label col-sm-2'
    .col-sm-7
      = f.text_area :description, class: 'form-control', rows: 3
  .form-group
    = f.label :image_url, class: 'control-label col-sm-2'
    .col-sm-5
      = f.text_field :image_url, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-8.form-actions
      .btn-toolbar
        .btn-group
          .btn.btn-default= f.submit

app/views/products/_product.html.haml
%tr
  %td= product.name
  %td= product.colour
  %td= product.description
  %td= product.image_url
  %td.btn.btn-group.text-right
    .btn.btn-sm.btn-default= link_to 'Show', product
    .btn.btn-sm.btn-default= link_to 'Edit', edit_product_path(product)
    .btn.btn-sm.btn-default= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }

app/views/products/edit.html.haml
%h1 Editing Product

= render 'form'

.col-sm-offset-2.col-sm-8
  = link_to 'Show', @product, class: 'btn btn-default'
  = link_to 'Back', products_path, class: 'btn btn-default'

app/views/products/index.html.haml
%p#notice= notice

%h1 Listing Products

%table.table.table-condensed.table-hover
  %thead
    %tr
      %th.col-sm-2 Name
      %th.col-sm-2 Colour
      %th.col-sm-4 Description
      %th.col-sm-2 Image url
      %th.col-sm-2

  %tbody
    = render @products

%br

= link_to 'New Product', new_product_path

app/views/products/new.html.haml
%h1 New Product

= render 'form'

.col-sm-offset-2.col-sm-8
  = link_to 'Back', products_path, class: 'btn btn-default'

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Colour:</strong>
  <%= @product.colour %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/shared/_nav.html.haml
<!-- Fixed navbar -->
%nav.navbar.navbar-inverse.navbar-fixed-top{role: 'navigation'}

  %div.container-fluid

    <!--Navigations Links on Left-->
    %ul.nav.navbar-nav.navbar-left#home
      %li
        = link_to 'Home', root_path

    %div.navbar-header
      %button.navbar-toggle{type: "button", data: {toggle: "collapse", target: ".navbar-collapse"}}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

    %div.navbar-collapse.collapse

      <!--Navigations Links on Right-->
      %ul.nav.navbar-nav.navbar-right#scrollSpy
        %li= link_to 'Products', products_path
        %li= link_to 'About', static_pages_about_path
        %li= link_to 'Contact Us', static_pages_contact_path

        - if user_signed_in?
          %li= link_to 'Logout', destroy_user_session_path, method: :delete
        - else
          %li= link_to 'Login', new_user_session_path

        %li.search-box
          = form_tag "/products", method: "get" do
            = label_tag :q, "Search for:"
            = text_field_tag :q
            = submit_tag "Search"

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/index.html.erb
<p><%= image_tag 'Ruhe_2014_Panorama.jpg', alt: image_alt('Ruhe_2014_Panorama.jpg'), class: 'img-responsive' %></p>

app/views/static_pages/landing_page.html.haml
%div.carousel.slide#carousel-example-generic{data: {ride: 'carousel'}}
  <!-- Indicators -->
  %ol.carousel-indicators
    %li.active{data: {target: '#carousel-example-generic', slide: {to: '0'}}}
    %li{data: {target: '#carousel-example-generic', slide: {to: '1'}}}
    %li{data: {target: '#carousel-example-generic', slide: {to: '2'}}}

  <!-- Wrapper for slides -->
  %div.carousel-inner{role: 'listbox'}
    - @products.each do |product|
      %div.item{class: product == @products.first && 'active'}
        = image_tag product.image_url
        %div.carousel-caption= product.name

  <!-- Controls -->
  %a.left.carousel-control{href: "#carousel-example-generic", role: "button", data: {slide: "prev"}}
    %span.glyphicon.glyphicon-chevron-left{aria: {hidden: "true"}}
    %span.sr-only Previous
  %a.right.carousel-control{href: "#carousel-example-generic", role: "button", data: {slide: "next"}}
    %span.glyphicon.glyphicon-chevron-right{aria: {hidden: "true"}}
    %span.sr-only Previous

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>